[package]
name = "env-sync"
version = "0.1.2"
edition = "2024"
authors = ["Nazeb Zurati"]
description = "A simple dotenv file syncer that keeps your messy .env in sync with your template, placing values in the correct order."
repository = "https://github.com/nazebzurati/env-sync"
license = "GPL-3.0-only"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
